### ISSUE TITLE
Quiz Grading is Incorrect

### ISSUE THREAD

**Issue by connork97** [learn-co-curriculum/python-p4-quiz-rest-apis#1]
### Canvas Link

https://learning.flatironschool.com/courses/6275/quizzes/46177

### Concern

Question 2: "What can the PATCH method do for us?" Seems to be incorrect in grading us.  Originally, I selected "Update an existing resource" and not "Create a new resource", but it only gave me partial credit.  When I selected both the next time it gave me full credit, but the message below "Create a new resource" read "Not quite!" followed by the explanation of why it was wrong to select that.

### Suggested Changes

The test just needs the "correct" vs "incorrect" answers to be adjusted accordingly is all.  The explanations are fine, just the grading itself.  Thanks!

**Comment by pgill97** [comment]
Fixed quiz
